export const GET_VALUE = 'GET_VALUE';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const DETAIL_PRODUCT='DETAIL_PRODUCT';
export const ADD_TO_CART='ADD_TO_CART';
export const SAVE_ADDRESS='SAVE_ADDRESS';
export const INCREMENT_QUANTITY='INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY='DECREMENT_QUANTITY';
export const ORDER_INDIVIDUAL_PRODUCT='ORDER_INDIVIDUAL_PRODUCT'
export const CHECKOUT_FROM_CART='CHECKOUT_FROM_CART'
export const EMPTY_CART='EMPTY_CART'

